### PR TITLE
Fix/Manifest view refreshes after rotating device

### LINKED ISSUE #3: Manifest view refreshes after rotating device
Open a manifest file and scroll to a random position. Rotate screen and you will find the page scroll back to top. Then I need to manually restore the position.

Before rotation:
Screen Shot 2022-03-04 at 8 17 11 PM

After rotation:
Screen Shot 2022-03-04 at 8 17 19 PM

I was testing on v4.1.4 on Android 10

### PR DESCRIPTION
**Pull request by Y-E-P**
* reworked live data
* added ability to restore scroll state on screen rotation
* added single shot loading data for manifest instead on recreating data each time on rotation

closes #3

### CODE REVIEW

File: app/src/main/java/com/sdex/activityrunner/manifest/ManifestViewerActivity.kt [hunk 1]
```diff
@@ -146,12 +152,28 @@ class ManifestViewerActivity : BaseActivity() {
...
                                 Configuration.UI_MODE_NIGHT_YES))
 
+    private fun scrollTo(yPosition: Int) {
+        scrollCallback = Runnable { binding.highlightView.scrollTo(0, yPosition) }
+        binding.highlightView.postDelayed(scrollCallback, 300)
+    }
+
+    override fun onDestroy() {
+        super.onDestroy()
+        scrollCallback?.let { binding.progress.removeCallbacks(it) }
```
Comment (sdex) [inline app/src/main/java/com/sdex/activityrunner/manifest/ManifestViewerActivity.kt:174]: The callback is posted to `highlightView` but removed from `progress`.

File: app/src/main/java/com/sdex/activityrunner/manifest/ManifestViewModel.kt [hunk 2]
```diff
@@ -11,13 +11,15 @@ import kotlinx.coroutines.launch
...
-    val manifestLiveData: LiveData<String> = _manifestLiveData
+    private val _manifestLiveData = MutableLiveData<String?>()
+    val manifestLiveData: LiveData<String?> = _manifestLiveData
 
     private var job: Job? = null
 
     fun loadManifest(packageName: String) {
         job?.cancel()
+        // parsing is one time operation, so check for filled live data to avoid unnecessary recreating
+        if(_manifestLiveData.value != null) return
```
Comment (sdex) [inline app/src/main/java/com/sdex/activityrunner/manifest/ManifestViewModel.kt:22]: Please remove the comment and add brackets for the `if` statement.

File: app/src/main/java/com/sdex/activityrunner/manifest/ManifestViewerActivity.kt [hunk 3]
```diff
@@ -152,10 +155,21 @@ class ManifestViewerActivity : BaseActivity() {
                         (resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK ==
                                 Configuration.UI_MODE_NIGHT_YES))
 
+    override fun onSaveInstanceState(outState: Bundle) {
```
Comment (sdex) [inline app/src/main/java/com/sdex/activityrunner/manifest/ManifestViewerActivity.kt:158]: How do you think, is it possible to use `onSaveInstanceState/onRestoreInstanceState` directly in the `HighlightJsView` to encapsulate saving and restoring scroll position?

File: app/src/main/java/com/sdex/activityrunner/manifest/ManifestViewerActivity.kt [hunk 4]
```diff
@@ -28,10 +28,12 @@ class ManifestViewerActivity : BaseActivity() {
     private val appPreferences by lazy { AppPreferences(this) }
     private lateinit var binding: ActivityManifestViewerBinding
     private lateinit var appPackageName: String
+    private var position = 0
 
     override fun onCreate(savedInstanceState: Bundle?) {
         try {
             super.onCreate(savedInstanceState)
+            position = savedInstanceState?.getInt(ARG_POSITION, 0) ?: 0
```
Comment (sdex) [inline app/src/main/java/com/sdex/activityrunner/manifest/ManifestViewerActivity.kt:36]: Please, move this out of `try/catch` block.

**Comment by sdex** [comment]
Looks great, thanks!
